# Generated by Django 4.2.4 on 2023-08-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, help_text='Ingrese sin puntos', max_length=8, null=True, verbose_name='D.N.I.')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField(help_text='dia/mes/año', max_length=6, verbose_name='Fecha de nacimiento')),
            ],
            options={
                'ordering': ('apellido', 'nombre'),
            },
        ),
    ]
