# Generated by Django 4.2.4 on 2023-08-15 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('apellido', 'nombre'), 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='persona',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Hombre'), ('X', 'Otro')], default='Femenino', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
