# Generated by Django 4.2.4 on 2023-08-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_alter_persona_options_persona_created_persona_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], default='Femenino', max_length=10, null=True),
        ),
    ]
