# Generated by Django 4.2.4 on 2023-08-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0003_alter_persona_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('C', 'Casado'), ('S', 'Soltero'), ('V', 'Viudo'), ('O', 'Otro')], default='Soltero', max_length=8, null=True),
        ),
    ]
