# Generated by Django 4.2.4 on 2023-08-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0004_persona_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('C', 'Casado'), ('S', 'Soltero'), ('V', 'Viudo'), ('O', 'Otro')], default='S', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], default='F', max_length=10, null=True),
        ),
    ]
