# Generated by Django 4.2.4 on 2023-08-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0005_alter_persona_estado_civil_alter_persona_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='vive',
            field=models.BooleanField(default=True),
        ),
    ]
