# Generated by Django 4.2.4 on 2023-08-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0006_persona_email_persona_vive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(default=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(default=True, help_text='dia/mes/año', max_length=6, verbose_name='Fecha de nacimiento'),
        ),
    ]
