# Generated by Django 4.2.4 on 2023-08-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0007_alter_persona_email_alter_persona_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='nombre@hotmail.com', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(default='10/10/10', help_text='dia/mes/año', max_length=6, verbose_name='Fecha de nacimiento'),
        ),
    ]
