# Generated by Django 4.2.4 on 2023-08-29 22:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0008_alter_persona_email_alter_persona_fecha_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='legajo',
            field=ckeditor.fields.RichTextField(default='Legajo de Persona'),
        ),
    ]
