# Generated by Django 4.2.4 on 2023-09-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0009_persona_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='avatar.png', upload_to='imagenes/', verbose_name='Foto 4x4'),
        ),
    ]
