# Generated by Django 4.2.4 on 2023-09-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0012_alter_persona_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
                'ordering': '',
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='estado_civil',
        ),
    ]
