# Generated by Django 4.2.4 on 2023-09-13 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0013_estadocivil_remove_persona_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Personas.estadocivil'),
            preserve_default=False,
        ),
    ]
