# Generated by Django 4.2.4 on 2023-10-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0014_persona_estado_civil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('domicilio', models.CharField(max_length=25)),
                ('provincia', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('sexo', models.CharField(blank=True, default='F', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Titular',
                'verbose_name_plural': 'Titulares',
                'ordering': '',
            },
        ),
    ]
